# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0015_auto_20161224_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrobj',
            name='formalname',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Формализованное наименование'),
        ),
        migrations.AlterField(
            model_name='addrobj',
            name='offname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Официальное наименование'),
        ),
    ]
