# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-08 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0016_auto_20200508_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socrbase',
            name='scname',
            field=models.CharField(default=' ', max_length=100, verbose_name='Краткое наименование типа объекта'),
        ),
        migrations.AlterField(
            model_name='socrbase',
            name='socrname',
            field=models.CharField(default=' ', max_length=100, verbose_name='Полное наименование типа объекта'),
        ),
    ]
